# Generated by Django 3.2.12 on 2022-09-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20220923_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact US', 'verbose_name_plural': 'Contact US'},
        ),
        migrations.AddField(
            model_name='visitorhistory',
            name='type_name_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
