# Generated by Django 3.2.12 on 2022-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_rename_type_name_id_visitorhistory_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='reviewcategory',
            index=models.Index(fields=['order'], name='review_cate_order_3a6774_idx'),
        ),
    ]
