# Generated by Django 3.2.12 on 2022-12-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20221128_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='DEFAULT VALUE', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['description'], name='name_descrip_a4fa94_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['short_description'], name='name_short_d_d4242b_idx'),
        ),
    ]
